title: Brendon Smith | Udacity
email: brendon.w.smith@gmail.com
description: >- # ignore newlines until "baseurl:"
  GitHub Pages Jekyll website for Udacity code on GitHub
url: "https://br3ndonland.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/udacity" # the subpath of your site, e.g. /blog
github_username: br3ndonland
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
include:
  - .htaccess
